# Generated by Django 4.0.7 on 2022-09-05 07:53

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('categoryName', models.CharField(max_length=255)),
                ('isDelete', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField(max_length=255)),
                ('cellPhone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('emial', models.EmailField(max_length=254)),
                ('profile', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('restaurantName', models.CharField(max_length=25)),
                ('social', models.CharField(max_length=25)),
                ('website', models.CharField(max_length=50)),
                ('isDelete', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tableName', models.CharField(max_length=255)),
                ('isDelete', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
